// Generated by gencpp from file kalman_zumy/ImuSrv.msg
// DO NOT EDIT!


#ifndef KALMAN_ZUMY_MESSAGE_IMUSRV_H
#define KALMAN_ZUMY_MESSAGE_IMUSRV_H

#include <ros/service_traits.h>


#include <kalman_zumy/ImuSrvRequest.h>
#include <kalman_zumy/ImuSrvResponse.h>


namespace kalman_zumy
{

struct ImuSrv
{

typedef ImuSrvRequest Request;
typedef ImuSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImuSrv
} // namespace kalman_zumy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kalman_zumy::ImuSrv > {
  static const char* value()
  {
    return "d41085fd9e23edf9efb8c5d896ef9228";
  }

  static const char* value(const ::kalman_zumy::ImuSrv&) { return value(); }
};

template<>
struct DataType< ::kalman_zumy::ImuSrv > {
  static const char* value()
  {
    return "kalman_zumy/ImuSrv";
  }

  static const char* value(const ::kalman_zumy::ImuSrv&) { return value(); }
};


// service_traits::MD5Sum< ::kalman_zumy::ImuSrvRequest> should match 
// service_traits::MD5Sum< ::kalman_zumy::ImuSrv > 
template<>
struct MD5Sum< ::kalman_zumy::ImuSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kalman_zumy::ImuSrv >::value();
  }
  static const char* value(const ::kalman_zumy::ImuSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kalman_zumy::ImuSrvRequest> should match 
// service_traits::DataType< ::kalman_zumy::ImuSrv > 
template<>
struct DataType< ::kalman_zumy::ImuSrvRequest>
{
  static const char* value()
  {
    return DataType< ::kalman_zumy::ImuSrv >::value();
  }
  static const char* value(const ::kalman_zumy::ImuSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kalman_zumy::ImuSrvResponse> should match 
// service_traits::MD5Sum< ::kalman_zumy::ImuSrv > 
template<>
struct MD5Sum< ::kalman_zumy::ImuSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kalman_zumy::ImuSrv >::value();
  }
  static const char* value(const ::kalman_zumy::ImuSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kalman_zumy::ImuSrvResponse> should match 
// service_traits::DataType< ::kalman_zumy::ImuSrv > 
template<>
struct DataType< ::kalman_zumy::ImuSrvResponse>
{
  static const char* value()
  {
    return DataType< ::kalman_zumy::ImuSrv >::value();
  }
  static const char* value(const ::kalman_zumy::ImuSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KALMAN_ZUMY_MESSAGE_IMUSRV_H
