// Generated by gencpp from file kalman_zumy/ImuSrvRequest.msg
// DO NOT EDIT!


#ifndef KALMAN_ZUMY_MESSAGE_IMUSRVREQUEST_H
#define KALMAN_ZUMY_MESSAGE_IMUSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kalman_zumy
{
template <class ContainerAllocator>
struct ImuSrvRequest_
{
  typedef ImuSrvRequest_<ContainerAllocator> Type;

  ImuSrvRequest_()
    {
    }
  ImuSrvRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImuSrvRequest_

typedef ::kalman_zumy::ImuSrvRequest_<std::allocator<void> > ImuSrvRequest;

typedef boost::shared_ptr< ::kalman_zumy::ImuSrvRequest > ImuSrvRequestPtr;
typedef boost::shared_ptr< ::kalman_zumy::ImuSrvRequest const> ImuSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kalman_zumy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::kalman_zumy::ImuSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kalman_zumy/ImuSrvRequest";
  }

  static const char* value(const ::kalman_zumy::ImuSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::kalman_zumy::ImuSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ImuSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kalman_zumy::ImuSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::kalman_zumy::ImuSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // KALMAN_ZUMY_MESSAGE_IMUSRVREQUEST_H
